"""
Central configuration for the Streamlit app: file paths and constants.
Kept separate from src/utils/config.py because that file references
placeholder filenames that don't match the actual pipeline outputs.
"""
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent

DATA_DIR = PROJECT_ROOT / "data"
PROCESSED_DIR = DATA_DIR / "processed"
RAW_DIR = DATA_DIR / "raw"
MODELS_DIR = PROJECT_ROOT / "models"
REPORTS_DIR = PROJECT_ROOT / "reports"
FIGURES_DIR = REPORTS_DIR / "figures"

# Data files
ML_FEATURES_FILE = PROCESSED_DIR / "portfolio_ml_features.csv"
STOCK_FEATURES_FILE = PROCESSED_DIR / "stock_features.csv"
STOCK_WEIGHTS_FILE = PROCESSED_DIR / "portfolio_stock_weights.csv"
SECTOR_WEIGHTS_FILE = PROCESSED_DIR / "portfolio_sector_weights.csv"
RISK_TARGETS_FILE = PROCESSED_DIR / "portfolio_risk_targets.csv"

# Model
MODEL_FILE = MODELS_DIR / "09_tuned_selected_model.joblib"

# Reports
FINAL_METRICS_FILE = REPORTS_DIR / "final_test_metrics.csv"
FINAL_PREDICTIONS_FILE = REPORTS_DIR / "final_test_predictions.csv"
FINAL_CONFUSION_FILE = REPORTS_DIR / "final_confusion_matrix.csv"
FINAL_CALIBRATION_FILE = REPORTS_DIR / "final_calibration_summary.csv"
FINAL_DECILES_FILE = REPORTS_DIR / "final_risk_deciles.csv"
FINAL_STABILITY_FILE = REPORTS_DIR / "final_test_stability.csv"
SHAP_IMPORTANCE_FILE = REPORTS_DIR / "shap_feature_importance.csv"
MODEL_COMPARISON_FILE = REPORTS_DIR / "model_comparison.csv"
RISK_TARGET_DIST_FILE = REPORTS_DIR / "risk_target_distribution.csv"
PORTFOLIO_SUMMARY_FILE = REPORTS_DIR / "portfolio_construction_summary.csv"

# Figures (pre-generated by the notebooks)
FIG_ROC = FIGURES_DIR / "final_test_roc_curve.png"
FIG_PR = FIGURES_DIR / "final_test_precision_recall_curve.png"
FIG_CALIBRATION = FIGURES_DIR / "final_test_calibration.png"
FIG_SHAP_GLOBAL = FIGURES_DIR / "shap_global_feature_importance.png"
FIG_SHAP_BEESWARM = FIGURES_DIR / "shap_beeswarm.png"
FIG_SHAP_LOCAL = [FIGURES_DIR / f"shap_local_explanation_{i}.png" for i in (1, 2, 3)]

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TARGET_LABEL = "5% portfolio drawdown within 10 trading days"
DEFAULT_THRESHOLD = 0.40

RISK_BANDS = [
    (0.00, 0.25, "Low", "#2ecc71"),
    (0.25, 0.40, "Moderate", "#f1c40f"),
    (0.40, 0.60, "Elevated", "#e67e22"),
    (0.60, 1.01, "High", "#e74c3c"),
]

SECTOR_COLORS = {
    "Financials": "#4C6FFF",
    "IT": "#00C2A8",
    "Energy": "#FF9F40",
    "FMCG": "#9B6BFF",
    "Automobile": "#FF6B6B",
    "Pharma": "#36C5F0",
    "Metals": "#B0A18E",
    "Infrastructure": "#F7B801",
    "Healthcare": "#7BD389",
    "Consumer Durables": "#FF8FB1",
    "Cement": "#8D99AE",
    "Power": "#FFD166",
    "Telecom": "#5E60CE",
}
